### ISSUE TITLE
Runtime exception about HxOverrides

### ISSUE THREAD

**Issue by gene-pavlovsky** [elsassph/haxe-modular#108]
Using GitHub version of modular (commit a46a26a5) and Haxe 4.1.5, I'm getting a runtime exception cause by this code:
`HxOverrides.now = performance.now.bind(performance);`

Console log:
> Uncaught ReferenceError: HxOverrides is not defined

**Comment by elsassph** [comment]
I see this code is generated for `Timer.stamp()`, but the issue doesn't happen with `master` version of Modular, as far as I can see.

**Comment by elsassph** [comment]
Can you confirm: are you using ES6 output?

**Comment by gene-pavlovsky** [comment]
We don't have the `-D js-es=6` option in the build files. Default is ES5, right?

**Comment by elsassph** [comment]
Yes. I'm doing a new branch with Haxe 4.2+ fixes, and supporting both ES5 and ES6 outputs.

**Comment by gene-pavlovsky** [comment]
At the moment we're stuck on Haxe 4.1.5 due to some libraries compatibility.
I'm not getting the runtime exception anymore, I think after I updated the haxe-modular npm package to 0.12.1.

**Comment by elsassph** [comment]
That's ok, the library is backwards compatible with Haxe up to 3.x.
