### ISSUE TITLE
"Uncaught ReferenceError: $global is not defined"

### ISSUE THREAD

**Issue by volth** [elsassph/haxe-modular#21]
Bundler strips the first two lines:
```
// Generated by Haxe 3.4.2
(function ($global) { "use strict";
```
And ```$global``` becomes undefined
It is [used by Haxe stdlib](https://github.com/HaxeFoundation/haxe/blob/3.4.2/std/js/Lib.hx#L105), without ```$global``` it is not possible to [use ArrayBuffer](https://github.com/HaxeFoundation/haxe/blob/3.4.2/std/js/html/compat/ArrayBuffer.hx#L57), without ArrayBuffer it is not possible to use ```haxe-ws```, etc.

**Comment by volth** [comment]
This quick fix https://github.com/elsassph/haxe-modular/compare/master...volth:patch-2 does help, but it might be better to preserve ```$global``` param instead of stripping it and let webpack add ```(function (global) { ```

**Comment by elsassph** [comment]
Yes, check the last haxelib release.
