### ISSUE TITLE
Splitting issue with some HTML compat classes

### ISSUE THREAD

**Issue by elsassph** [elsassph/haxe-modular#23]
Review identification of classes with "compat" fallback, eg:
```javascript
var DataView = $global.DataView || js_html_compat_DataView;
```
At least one class (`DataView`) gets split without its compat class - it will cause a JS exception in browser needing the compat class.

http://api.haxe.org/js/html/compat/index.html

**Comment by kLabz** [comment]
I ran into this, do you have a workaround for this bug?

**Comment by elsassph** [comment]
Possibly referencing explicitly the compat class from code using the DataView.

**Comment by kLabz** [comment]
I don't really know what's using DataView under the hood (maybe even simple js getters/setters? [[1]](https://github.com/HaxeFoundation/haxe/issues/4259#issuecomment-113268220))

For now I am patching directly in my local haxe std, commenting the import in DataView.hx to avoid loading the compatibility class.

Do you have any lead on how to fix this issue?

**Comment by elsassph** [comment]
It would be used by things like `haxe.io.Bytes` I think - it should be visible in the generated code.

The fix requires to add some more logic in the parser when the dependency graph is constructed - somehow the link between `DataView` and the compat class is missing.

**Comment by kLabz** [comment]
It happens when I use js.Browser (both with import and direct use) with Haxe 4, I can't really avoid that so I'll stick with the dirty fix for now (and try to see what's happening in haxe modular when I find some time to do so).
