### ISSUE TITLE
Classes with underscores not loaded

### ISSUE THREAD

**Issue by mastef** [elsassph/haxe-modular#45]
`Bundle.load(fla.a.b_c_d.e_f_g.ABC).then(function(_){`
will try to load
`fla_a_b_c_d_e_f_g_ABC.js`
instead of
`fla_a_b_$c_$d_e_$f_$g_ABC.js`

To fix, change
[`var module = t.module.split('.').join('_');`](https://github.com/elsassph/haxe-modular/blob/master/src/Bundle.hx#L16) to
`var module = t.module.split('_').join('_$').split('.').join('_');`

**Comment by elsassph** [comment]
Fixed, for after 0.8.0
