### ISSUE TITLE
npm libraries are not getting packaged, so cannot 'require'

### ISSUE THREAD

**Issue by dionjwa** [elsassph/haxe-modular#53]
[testapp.zip](https://github.com/elsassph/haxe-modular/files/1699767/testapp.zip)

    Unzip
    npm i
    haxelib install build.hxml
    node_modules/.bin/webpack-dev-server --watch --content-base client/web

Go to the browser, and see the error `Cannot read property 'react' of undefined`. 

It feels like I'm missing something really obvious and stupid, but for the life of me I can't figure it out.

**Comment by elsassph** [comment]
Aha ok found it: you have `-lib modular:0.9.3` in your HXML. It conflicts with the generated output that Webpack consumes.

**Comment by elsassph** [comment]
I think we need to add a safeguard and throw and error in the Haxe loader if this is identified.
