### ISSUE TITLE
haxe-modular vs hxgenjs

### ISSUE THREAD

**Issue by fullofcaffeine** [elsassph/haxe-modular#89]
It'd be nice if `hxgenjs` was mentioned in the README as a possible alternative with pros/cons of using it or `haxe-modular`. I myself am not sure of the differences and why `hxgenjs` (which seems to be a more recent project) is not used here, for example.

**Comment by elsassph** [comment]
Fair enough to ask.

`hxgenjs` have different goals: it's meant to emit individual JS files, which have to be bundled afterwards. It doesn't also have any helpers for allowing code splitting, though this would be feasible to add, and it doesn't emit sourcemaps.

Modular was meant to be a standalone solution, purely for adding code splitting while respecting exactly the Haxe JS output, including full support for sourcemaps.

Later I leveraged it the Webpack loader to be able to, again, use naturally the Haxe JS output in Webpack without emitting JS files.

**Comment by fullofcaffeine** [comment]
Thanks a lot for the reply, Philippe.

I was under the impression `haxe_modular` was refactored at some point to use `hxgenjs`, since `hxgenjs` aims at being a generic framework for building js generators with Haxe. Then I couldn't find any mention of it in the source code and got confused.

Thanks a lot for `haxe-modular and haxe-react btw, I decided to try it out for a new project and so far it's working great. It's also the first time I'm actually using WebPack and I just added SASS compilation and it was easy as pie. The https://github.com/elsassph/webpack-haxe-example example was super useful!

**Comment by elsassph** [comment]
I've considered using hxgenjs internally, and replacing the JS output but that'd be a huge rewrite for unsure benefits.

**Comment by fullofcaffeine** [comment]
Understood. `haxe-modular` also uses the js generator API right?

**Comment by elsassph** [comment]
No, Modular post-processes the regular Haxe JS output.

**Comment by fullofcaffeine** [comment]
Oh, interesting approach! I'll have a look.
